package dafen.dao;

import dafen.bean.DepartmentDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DepartmentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int insert(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int insertSelective(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    DepartmentDO selectByPrimaryKey(Integer id);

    /**
     *
     * @return
     */
    List<DepartmentDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int updateByPrimaryKeySelective(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int updateByPrimaryKey(DepartmentDO record);
}