package dafen.dao;

import dafen.bean.ScoreDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ScoreDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int insert(ScoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int insertSelective(ScoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    ScoreDO selectByPrimaryKey(int id);

    List<ScoreDO> selectByUserId(@Param("userId")int userId,@Param("start")int start,@Param("end")int end);
    List<ScoreDO> selectByDepartmentId(@Param("departmentId")int departmentId,@Param("start")int start,@Param("end")int end);
    List<ScoreDO> selectByTimes(@Param("times")int times,@Param("start")int start,@Param("end")int end);

    List<ScoreDO> selectByTimesAndUserId(@Param("userId")int userId,@Param("times")int times);
    List<ScoreDO> selectByTimesAndDepId(@Param("departmentId")int departmentId,@Param("times")int times);

    /**
     * 验证数据是否存在
     * @param userId
     * @param departmentId
     * @param times
     * @return
     */
    ScoreDO selectByDepUserIdTimes(@Param("userId")int userId,
                                   @Param("departmentId")int departmentId,@Param("times")int times);

    /**
     * 仅返回times 编号组
     * @param userId
     * @param departmentId
     * @param start
     * @param end
     * @return
     */
    List<ScoreDO> selectByCondition(int userId,int departmentId,int start,int end);

    /**
     * 超级管理员根据次数导出该期的数据
     * @param times
     * @return
     */
    List<ScoreDO> exportScoreByTimes(int times);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int updateByPrimaryKeySelective(ScoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int updateByPrimaryKey(ScoreDO record);
}