package dafen.dao;

import dafen.bean.ScoreDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ScoreDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int insert(ScoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int insertSelective(ScoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    ScoreDO selectByPrimaryKey(Integer id);
    List<ScoreDO> selectByUserId(Integer userId,int start,int end);
    List<ScoreDO> selectByDepartmentId(Integer departmentId,int start,int end);
    List<ScoreDO> selectByTimes(Integer times,int start,int end);
    List<ScoreDO> selectByTimesAndUserId(Integer userId,Integer times);
    List<ScoreDO> selectByTimesAndDepId(Integer departmentId,Integer times);

    /**
     * 仅返回times 编号组
     * @param userId
     * @param departmentId
     * @param start
     * @param end
     * @return
     */
    List<ScoreDO> selectByCondition(int userId,int departmentId,int start,int end);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int updateByPrimaryKeySelective(ScoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int updateByPrimaryKey(ScoreDO record);
}