package dafen.dao;

import dafen.bean.ScoreDO;
import dafen.bean.SelfDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ScoreDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int insert(ScoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int insertSelective(ScoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    ScoreDO selectByPrimaryKey(int id);

    /**
     * 验证数据是否存在
     * @param userId
     * @param departmentId
     * @param times
     * @return
     */
    ScoreDO selectByDepUserIdTimes(@Param("userId")int userId,@Param("departmentId")int departmentId,@Param("times")int times);

    /**
     * 获取用户的打分次数列表
     * @param userId
     * @param start
     * @param end
     * @return
     */
    List<SelfDO> selectByUserId(@Param("userId")int userId,@Param("start")int start,@Param("end")int end);

    /**
     * 根据部门id，获取打分列表
     * @param departmentId
     * @param start
     * @param end
     * @return
     */
    List<SelfDO> selectByDepartmentId(@Param("departmentId")int departmentId,@Param("start")int start,@Param("end")int end);
    /**
     * 查询次数列表
     * @param start
     * @param end
     * @return
     */
    List<SelfDO> getTimes(@Param("start")int start, @Param("end")int end);


    /**
     * 根据次数，获取详细打分信息
     * @param times
     * @return
     */
    List<ScoreDO> selectByTimes(@Param("times")int times);

    /**
     * 根据用户id及打分次数编号，获取详细的打分信息
     *
     * @param userId
     * @param times
     * @return
     */
    List<ScoreDO> selectByTimesAndUserId(@Param("userId")int userId,@Param("times")int times);

    /**
     * 根据部门编号及打分次数编号，获取详细的打分信息
     * @param departmentId
     * @param times
     * @return
     */
    List<ScoreDO> selectByTimesAndDepId(@Param("departmentId")int departmentId,@Param("times")int times);


    /**
     * 超级管理员根据次数导出该期的数据
     * @param times
     * @return
     */
    List<ScoreDO> exportScoreByTimes(int times);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int updateByPrimaryKeySelective(ScoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    int updateByPrimaryKey(ScoreDO record);
}