package dafen.bean;

import java.util.Date;

public class ScoreDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.user_id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.department_id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.department_id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.scord
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Float scord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.reason
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.explain_in_detail
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private String explainInDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.create_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.update_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.delete_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Integer deleteTime;

    private UserDO userDO;

    private DepartmentDO departmentDO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.user_id
     *
     * @return the value of score.user_id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.user_id
     *
     * @param userId the value for score.user_id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.department_id
     *
     * @return the value of score.department_id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.department_id
     *
     * @param departmentId the value for score.department_id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    public Integer getTimes() {
        return times;
    }

    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.scord
     *
     * @return the value of score.scord
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Float getScord() {
        return scord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.scord
     *
     * @param scord the value for score.scord
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setScord(Float scord) {
        this.scord = scord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.reason
     *
     * @return the value of score.reason
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.reason
     *
     * @param reason the value for score.reason
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.explain_in_detail
     *
     * @return the value of score.explain_in_detail
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public String getExplainInDetail() {
        return explainInDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.explain_in_detail
     *
     * @param explainInDetail the value for score.explain_in_detail
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setExplainInDetail(String explainInDetail) {
        this.explainInDetail = explainInDetail == null ? null : explainInDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.create_time
     *
     * @return the value of score.create_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.create_time
     *
     * @param createTime the value for score.create_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.update_time
     *
     * @return the value of score.update_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.update_time
     *
     * @param updateTime the value for score.update_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.delete_time
     *
     * @return the value of score.delete_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Integer getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.delete_time
     *
     * @param deleteTime the value for score.delete_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setDeleteTime(Integer deleteTime) {
        this.deleteTime = deleteTime;
    }

    public UserDO getUserDO() {
        return userDO;
    }

    public void setUserDO(UserDO userDO) {
        this.userDO = userDO;
    }

    public DepartmentDO getDepartmentDO() {
        return departmentDO;
    }

    public void setDepartmentDO(DepartmentDO departmentDO) {
        this.departmentDO = departmentDO;
    }
}