package dafen.bean;

import java.util.Date;

public class DepartmentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.d_name
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.create_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.update_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.delete_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    private Integer deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.d_name
     *
     * @return the value of department.d_name
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.d_name
     *
     * @param dName the value for department.d_name
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.create_time
     *
     * @return the value of department.create_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.create_time
     *
     * @param createTime the value for department.create_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.update_time
     *
     * @return the value of department.update_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.update_time
     *
     * @param updateTime the value for department.update_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.delete_time
     *
     * @return the value of department.delete_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public Integer getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.delete_time
     *
     * @param deleteTime the value for department.delete_time
     *
     * @mbg.generated Sun Oct 20 16:15:44 CST 2019
     */
    public void setDeleteTime(Integer deleteTime) {
        this.deleteTime = deleteTime;
    }
}